<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bank" nsURI="http://www.example.com/bank" nsPrefix="bank">
  <eClassifiers xsi:type="ecore:EClass" name="Bank">
    <eStructuralFeatures xsi:type="ecore:EReference" name="managers" upperBound="-1"
        eType="#//Manager" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="#//Account" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
        eType="#//Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manager" upperBound="-1"
        eType="#//Manager" eOpposite="#//Manager/clients"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="#//Account" eOpposite="#//Account/owners"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sponsorships" upperBound="-1"
        eType="#//Client"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Manager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clients" upperBound="-1"
        eType="#//Client" eOpposite="#//Client/manager"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owners" upperBound="-1"
        eType="#//Client" eOpposite="#//Client/accounts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overdraft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cards" upperBound="-1"
        eType="#//Card"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//CardType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardType"/>
</ecore:EPackage>
